### ISSUE TITLE
Upgrade to future versions of grib-api

### ISSUE THREAD

**Issue by jnyrup** [0x1mason/GribApi.NET#31]
Hi Eric.

You might have noticed that several versions of the GRIB-API has been released since your release gribApi.NET. 
IIRC you mentioned somewhere that you don't use your tool that much yourself anymore.

So my question is about how to update to a new version of the grib api. 
I read in the release notes that your OpenMP code had been included.
Are the difference between your fork of grib api and the official sources small enough, such that an update could be done by other than you, or even automated?

**Comment by 0x1mason** [comment]
It's possible. The only real difference in the code itself now is that I removed cases where GribApi would exit on error by design and added exceptions. Someone could do a diff and create a patch with it, but for future updates would need to search the code and make changes. Not that hard, as long as you're not terrified of C.

The major difficulty would be VS project files. I had to make a number of changes to various dependencies to get everything working. Basically, I'd need someone who knew what they were doing or willing to grind through it.

I'm willing to take a look at updating though. Seems like some people are using it.

**Comment by 0x1mason** [comment]
I simplified the native code portion with the goal of ultimately have the C# in a separate project. I thought that might encourage folks to contribute.

Here's the simplified native project: https://github.com/0x1mason/GribApi.XP/blob/master/README.md

**Comment by 0x1mason** [comment]
@jnyrup Is this a general question or is there a specific feature you're waiting for?

**Comment by jnyrup** [comment]
It was mostly a general question.
To my knowledge I'm not affected by any bugs, but I always gets curious when seeing a lot of bug fixes in release notes.

**Comment by 0x1mason** [comment]
I'll try to get to this soon. I just moved and have not setup my home dev environment yet.

**Comment by 0x1mason** [comment]
I'll start working on updating to 1.18.

**Comment by 0x1mason** [comment]
This is satisfied by v1.0.0.
