### ISSUE TITLE
Not Thread Safe

### ISSUE THREAD

**Issue by IdahoSixString** [0x1mason/GribApi.NET#54]
Unfortunately, due to my previous post of the callback delegate bug. This also invalidates the claim that this library is thread safe. 

Actually has some fun results when degribing files across multiple threads IE different parameters showing up in different files..

**Comment by 0x1mason** [comment]
Is this true for the 1.0 Beta?

**Comment by IdahoSixString** [comment]
Just brief testing it doesn't seem to be an issue on 1.0

If you don't mind me asking what was the change from 0.7... to 1.0?

**Comment by 0x1mason** [comment]
Lots of small tweaks, one of which was fixing the callback delegate issue.
Also upgraded to grib_api v1.19. I hope to get a last round of changes in
and release 1.0 soon(ish).

On Jun 23, 2017 5:21 PM, "IdahoSixString" <notifications@github.com> wrote:

Just brief testing it doesn't seem to be an issue on 1.0

If you don't mind me asking what was the change from 0.7... to 1.0?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/0x1mason/GribApi.NET/issues/54#issuecomment-310776114>,
or mute the thread

**Comment by IdahoSixString** [comment]
So I take it each grib object gets its own instance of the degrib dll?
________________________________

**Comment by 0x1mason** [comment]
@IdahoSixString I'm afraid I don't understand what you mean about the DLL. When your app loads GribApi.NET, it loads the native DLL into memory once. Most of the objects I've created correspond to structs or handles in the original library.

**Comment by IdahoSixString** [comment]
How are you keeping things thread safe now?
________________________________

**Comment by 0x1mason** [comment]
When i first started working on this project, grib_api only supported Linux
threads. I added suppport for OpenMP, which is a crossplatform abstraction
layer for parallel processing, because MSCRT supports OpenMP mutexes. They
eventually merged my patch.

All that is to say, threadsafety is mostly maintained at the native level.
That said, neither grib_api nor GribApi.NET are 100% threadsafe, but almost
nothing complex ever is. The problems should only be edge cases, tho.

**Comment by 0x1mason** [comment]
Closing this as resolved by v1.0.0-beta. Please lmk if it's still an issue.
