### ISSUE TITLE
Incompatibility with ArcGis Runtime

### ISSUE THREAD

**Issue by SandiaDeDia** [0x1mason/GribApi.NET#58]
Hi, I think I just came across an incompatibility between Grib.Api (v0.7.1) and  Esri.ArcGISRuntime (v10.2.7.1234).  What I have done is:

1) In a new fresh wpf  project added the Grip.Api and Esri.ArcGISRuntime  Nugget libraries

3) In the XAML added 2 lines to make use of Arcgis:
       <Window  .......  xmlns:esri="http://schemas.esri.com/arcgis/runtime/2013" ........>
        <Grid><esri:SceneView x:Name="sceneView" /><Grid>

4) In MainWindow added one line of code to read a file: 
          new GribFile(@"C:\myFolder\myFile.grb2").First();

Using both libraries independently they work fine, but using them together I get a system.AccessViolationException in the GribFile line. Hope this helps.

Thanks

**Comment by IdahoSixString** [comment]
I'm assuming somewhere you are binding to new GribFile(@"C:\myFolder\myFile.grb2").First();, or at least the geoSpatial values, or something else that is a part of that object in your XAML somewhere? If so, the simplest solution will be to actually copy all the data out of the grib file into your own DTO to avoid this AccessViolationException. This problem occurs because all the IEnumerable's are evaluated lazily and the handle is kept in the underlying POCO objects, which when you want to read another file that handle is no longer valid but still tries to access memory and thus throws the error. See #50 if you would like to see how I handled my DTO.

**Comment by SandiaDeDia** [comment]
Hi, sorry for my late reply. Yes, I think this will help us control the error. I will let you know.
Thanks a lot for clear explanation and for the library!!!!!

**Comment by IdahoSixString** [comment]
Just as a heads up I am not the one who created the library I am just another user such as yourself. :)
